### ISSUE TITLE
Syncing without google account

### ISSUE THREAD

**Issue by sjdrc** [petko10/real-time-tab-sync#10]
Hi there, I've just found your extension and it looks like exactly what I need! However, I use [Ungoogled Chromium](https://github.com/Eloston/ungoogled-chromium) instead of Google Chrome for privacy reasons, which means that I can't use your extension :(

Would it be possible in future to support my use case?

**Comment by v-ko** [comment]
Hi, I'm sorry but it 's not in the scope of the project. It would require a substantial change in the way the extension works, since synchronization relies mostly on the Chrome data sync service. To sync data in real time you need a stable server (peer to peer connections are trickier to setup and more unreliable), and I have no intention on creating such a service for the extension.
