### ISSUE TITLE
Sync does not run anymore

### ISSUE THREAD

**Issue by caspertech1** [petko10/real-time-tab-sync#8]
it used to work fine until recent update. Nothing happen after browser is launched. Autosync setting is turned on. It doesnt work regardless the chrome default startup option is changed. All chrome sync settings are turned on.
I disabled and reenabled the extension. It turned to red now even though previously it didn't sync, it was green.

**Comment by v-ko** [comment]
Can you open the extension settings, then the background page for RTTS and copy the console messages. Mind you that may contain URL from the open tabs since the extension was started.

**Comment by AlgorithMan-de** [comment]
I have the same problem. I think it's an issue with Chrome 80.

**Comment by AlgorithMan-de** [comment]
Here is the output from my background page console messages:

`-----Starting up-----
background.js:758 [chrome.runtime.onStartup]
background.js:758 [windowIsPresent] Windows count:  1
background.js:758 [updateSyncAllowedState] normalWindowPresent:  true  (should be true)
background.js:758 [updateSyncAllowedState] allTabsHaveCompletedLoading:  true  (should be true)
background.js:758 [allowSyncing]
background.js:758 [updateBrowserIcon]
background.js:758 [Startup] autoSyncEnabled:  true
background.js:758 [Startup] syncAll setting:  true
background.js:758 [updateBrowserIcon]
background.js:758 [updateSyncAllowedState] normalWindowPresent:  true  (should be true)
background.js:758 [updateSyncAllowedState] allTabsHaveCompletedLoading:  true  (should be true)
background.js:758 [mergeTabsFromSync]
background.js:758 [updateSyncAllowedState] normalWindowPresent:  true  (should be true)
background.js:758 [updateSyncAllowedState] allTabsHaveCompletedLoading:  true  (should be true)
background.js:758 [updateBrowserIcon]
background.js:758 [updateStorageFromTabs_directly]
background.js:758 [updateStorageFromTabs_directly] returnVal.syncTabs: false. Creating an empty array.
background.js:758 [diffCurrentTabsTo]
background.js:758 [diffCurrentTabsTo] chrome.tabs.query(query_obj) returned: 
background.js:758 [updateStorageFromTabs_directly]diffCurrentTabsTo ruturns undefined var-s . Returning.
background.js:758 [updateBrowserIcon]`

The thing is - I believe that RTTS still works partially (so the output should be fine). Because I had turned RTTS off, then closed some tabs, then turned RTTS on again and it opened the tabs again that I had closed. So it seems it still "synchronizes" with the machine it runs on - just not with other machines

**Comment by AlgorithMan-de** [comment]
I guess RTTS takes the URLs from chromes built-in history (where you can see which tabs are open on other devices). And it seems like chrome 80 has changed the way it stores them - when you go to your history, it now orders the tabs by the device they're opened on - I think this was different before(?)

**Comment by caspertech1** [comment]
Here is my console message...

background.js:758 -----Starting up-----
background.js:758 [chrome.runtime.onStartup]
background.js:758 [windowIsPresent] Windows count:  1
background.js:758 [updateSyncAllowedState] normalWindowPresent:  true  (should be true)
background.js:758 [updateSyncAllowedState] allTabsHaveCompletedLoading:  true  (should be true)
background.js:758 [allowSyncing]
background.js:758 [updateBrowserIcon]
background.js:758 [Startup] autoSyncEnabled:  true
background.js:758 [Startup] syncAll setting:  true
background.js:758 [updateBrowserIcon]
background.js:758 [updateSyncAllowedState] normalWindowPresent:  true  (should be true)
background.js:758 [updateSyncAllowedState] allTabsHaveCompletedLoading:  true  (should be true)
background.js:758 [mergeTabsFromSync]
background.js:758 [updateSyncAllowedState] normalWindowPresent:  true  (should be true)
background.js:758 [updateSyncAllowedState] allTabsHaveCompletedLoading:  true  (should be true)
background.js:758 [updateBrowserIcon]
background.js:758 [updateTabsFromStringList] syncTabs length:  1 , do_merge:  true
background.js:758 [diffCurrentTabsTo]
background.js:758 [diffCurrentTabsTo] chrome.tabs.query(query_obj) returned: 
background.js:758 [updateTabsFromStringList] diffCurrentTabsTo returned undefined var(s). Returning.
background.js:758 [updateStorageFromTabs_directly]
background.js:758 [diffCurrentTabsTo]
background.js:758 [diffCurrentTabsTo] chrome.tabs.query(query_obj) returned: 
background.js:758 [updateStorageFromTabs_directly]diffCurrentTabsTo ruturns undefined var-s . Returning.
background.js:758 [updateBrowserIcon]
popup.js:96 [popup] autoSyncEnabled:  true
popup.js:96 [popup] syncAll:  true

**Comment by caspertech1** [comment]
This is my console message after i disabled and reenabled the extension. It turned to red now.

background.js:758 -----Starting up-----
background.js:758 [Startup] autoSyncEnabled:  true
background.js:758 [Startup] syncAll setting:  true
background.js:758 [updateBrowserIcon]
2background.js:758 [updateSyncAllowedState] normalWindowPresent:  false  (should be true)
popup.js:96 [popup] autoSyncEnabled:  true
popup.js:96 [popup] syncAll:  true
popup.js:96 [popup] autoSyncEnabled:  true
popup.js:96 [popup] syncAll:  true

**Comment by MarkysMarks** [comment]
Same problem here with

OS: Windows 7 x64 Prof. with SP1
Chrome Version 80.0.3987.116 (Offizieller Build) (64-Bit)
Plugin Version: 1.3.0

**Comment by v-ko** [comment]
Ok, I believe I found the problems. The check for normal windows was buggy and the check for the pinned tabs setting returned True on initialization  => if you had no pinned tabs - no tabs were synced. I'll upload the new version with the fixes (1.3.1, https://github.com/petko10/real-time-tab-sync/commit/2dc1c80c260d99aaa18d27d3dc6f6f3babc7dd77 ), but it might take a few days for it to move past Chrome web store moderation.

Thank you all for taking the time to report the issues.

**Comment by v-ko** [comment]
Actually the update is live already. Do tell if the problem persists.
